scripts:
- /libraries/backlift-reloader.js
- /libraries/jquery.js
- /libraries/underscore.js
- /libraries/backbone.js
- /**/*.js

styles:
- /bootstrap*.css
- /**/*.css

compile:
- /**/*.scss

include:
  admin: 
  - github.com/backlift/backlift-admin
  libraries: 
  - gist.github.com/backlift/5325013 # backlift-reloader.js
  - github.com/backlift/backbone-bundle/tree/20130406
