scripts:
- /libraries/backlift-reloader.js
- /libraries/underscore/underscore.js
- /libraries/backbone/backbone.js
- /*.js

styles:
- /bootstrap*.css
- /*.css

compile:
- /**/*.scss

include:
    admin: 
    - github.com/backlift/backlift-admin
    libraries: 
    - gist.github.com/backlift/5325013 # backlift-reloader.js
    libraries/backbone:
    - github.com/documentcloud/backbone/tree/1.0.0
    libraries/underscore:
    - github.com/documentcloud/underscore/tree/1.4.4