scripts:
- /libraries/scripts/backlift-reloader.js
- /libraries/scripts/jquery.js
- /libraries/scripts/underscore.js
- /libraries/scripts/backbone.js
- /*.js

styles:
- /bootstrap*.css
- /*.css

compile:
- /**/*.scss

include:
  admin: 
  - github.com/backlift/backlift-admin
  libraries/scripts: 
  - gist.github.com/backlift/5325013 # backlift-reloader.js
  libraries:
  - github.com/backlift/backbone-bundle/tree/20130406

optimize: no